/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zwc' at '17-5-2 下午1:28' with Gradle 2.14
 *
 * @author zwc, @date 17-5-2 下午1:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
